[package]
name = "fluent-uri-bench"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies.fluent-uri]
path = ".."

[[bench]]
name = "bench"
harness = false

[dev-dependencies]
ada-url = "3.3"
criterion = "0.7"
iref = "3.1.3"
iri-string = "0.7.0"
oxiri = "0.2.2"
url = "2.5.0"
